create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  customer_code bigint generated by default as identity unique,
  customer_name text not null,
  mobile text,
  address text,
  village text,
  customer_type text not null default 'Household' check (customer_type in ('Household','Shop','Hotel','Restaurant','Institution','Other')),
  default_rate_per_liter numeric(10,2) not null default 0 check (default_rate_per_liter >= 0),
  default_morning_qty numeric(10,3) not null default 0 check (default_morning_qty >= 0),
  default_evening_qty numeric(10,3) not null default 0 check (default_evening_qty >= 0),
  billing_cycle text not null default 'Monthly' check (billing_cycle in ('Daily','Weekly','10 Day','Monthly','Manual')),
  opening_balance numeric(12,2) not null default 0,
  status text not null default 'active' check (status in ('active','inactive')),
  start_date date not null default (timezone('Asia/Kolkata', now()))::date,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_milk_deliveries (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete restrict,
  delivery_date date not null default (timezone('Asia/Kolkata', now()))::date,
  shift public.shift_type not null,
  milk_type text not null default 'Mixed' check (milk_type in ('Cow','Buffalo','Mixed','Other')),
  quantity_liters numeric(10,3) not null check (quantity_liters > 0),
  rate_per_liter numeric(10,2) not null check (rate_per_liter >= 0),
  amount numeric(12,2) generated always as (round(quantity_liters * rate_per_liter, 2)) stored,
  delivery_status text not null default 'Delivered' check (delivery_status in ('Delivered','Skipped','Returned')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_payments (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete restrict,
  payment_date date not null default (timezone('Asia/Kolkata', now()))::date,
  amount_paid numeric(12,2) not null check (amount_paid > 0),
  payment_mode text not null default 'Cash' check (payment_mode in ('Cash','UPI','Bank Transfer','Cheque','Other')),
  reference_no text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_customers_status on public.customers(status);
create index if not exists idx_customers_name on public.customers(customer_name);
create index if not exists idx_customer_deliveries_customer_date on public.customer_milk_deliveries(customer_id, delivery_date desc);
create index if not exists idx_customer_deliveries_date_shift on public.customer_milk_deliveries(delivery_date desc, shift);
create index if not exists idx_customer_payments_customer_date on public.customer_payments(customer_id, payment_date desc);

create trigger customers_set_updated_at before update on public.customers for each row execute function public.set_updated_at();
create trigger customer_deliveries_set_updated_at before update on public.customer_milk_deliveries for each row execute function public.set_updated_at();
create trigger customer_payments_set_updated_at before update on public.customer_payments for each row execute function public.set_updated_at();

alter table public.customers enable row level security;
alter table public.customer_milk_deliveries enable row level security;
alter table public.customer_payments enable row level security;

create policy "customers_authenticated_read" on public.customers for select to authenticated using (true);
create policy "customers_manager_owner_insert" on public.customers for insert to authenticated with check (public.is_manager_or_owner());
create policy "customers_manager_owner_update" on public.customers for update to authenticated using (public.is_manager_or_owner()) with check (public.is_manager_or_owner());
create policy "customers_owner_delete" on public.customers for delete to authenticated using (public.is_owner());

create policy "customer_deliveries_authenticated_read" on public.customer_milk_deliveries for select to authenticated using (true);
create policy "customer_deliveries_authenticated_insert" on public.customer_milk_deliveries for insert to authenticated with check (auth.uid() is not null);
create policy "customer_deliveries_manager_owner_update" on public.customer_milk_deliveries for update to authenticated using (public.is_manager_or_owner()) with check (public.is_manager_or_owner());
create policy "customer_deliveries_manager_owner_delete" on public.customer_milk_deliveries for delete to authenticated using (public.is_manager_or_owner());

create policy "customer_payments_manager_owner_read" on public.customer_payments for select to authenticated using (public.is_manager_or_owner());
create policy "customer_payments_manager_owner_insert" on public.customer_payments for insert to authenticated with check (public.is_manager_or_owner());
create policy "customer_payments_owner_update" on public.customer_payments for update to authenticated using (public.is_owner()) with check (public.is_owner());
create policy "customer_payments_owner_delete" on public.customer_payments for delete to authenticated using (public.is_owner());

create or replace view public.customer_ledger_summary
with (security_invoker = true)
as
select
  c.id as customer_id,
  c.customer_code,
  c.customer_name,
  c.mobile,
  c.address,
  c.village,
  c.customer_type,
  c.billing_cycle,
  c.default_rate_per_liter,
  c.default_morning_qty,
  c.default_evening_qty,
  c.opening_balance,
  c.status,
  coalesce(d.total_liters, 0)::numeric(14,3) as total_liters,
  coalesce(d.total_sales, 0)::numeric(14,2) as total_sales,
  coalesce(p.total_paid, 0)::numeric(14,2) as total_paid,
  (c.opening_balance + coalesce(d.total_sales, 0) - coalesce(p.total_paid, 0))::numeric(14,2) as outstanding_amount
from public.customers c
left join (
  select customer_id,
         sum(quantity_liters) filter (where delivery_status = 'Delivered') as total_liters,
         sum(amount) filter (where delivery_status = 'Delivered') as total_sales
  from public.customer_milk_deliveries
  group by customer_id
) d on d.customer_id = c.id
left join (
  select customer_id, sum(amount_paid) as total_paid
  from public.customer_payments
  group by customer_id
) p on p.customer_id = c.id;

grant select on public.customer_ledger_summary to authenticated;
